#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    turnGyro,       sensorGyro)
#pragma config(Sensor, in2,    lfLeft,         sensorLineFollower)
#pragma config(Sensor, in3,    lfMid,          sensorLineFollower)
#pragma config(Sensor, in4,    lfRight,        sensorLineFollower)
#pragma config(Sensor, dgtl1,  rtZero,         sensorTouch)
#pragma config(Sensor, dgtl2,  lftZero,        sensorTouch)
#pragma config(Sensor, dgtl3,  sriseClaw,      sensorDigitalOut)
#pragma config(Sensor, I2C_1,  bl,             sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  br,             sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  aBotL,          sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  aBotR,          sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_5,  aTopL,          sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_6,  aTopR,          sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           fl,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           fr,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           bl,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port5,           br,            tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port6,           aBotL,         tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port7,           aBotR,         tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port8,           aTopL,         tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port9,           aTopR,         tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_6)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#include "Auton.h"
#include "Menu.h"
#include "Constants.h"

#include "driveAuton.h"
#include "driveUser.h"

#include "liftAuton.h"
#include "liftUser.h"

#include "intakeControl.h"

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	startTask(Menu);
  bStopTasksBetweenModes = true;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	startTask(Menu);
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	startTask(Menu);

	while (true)
	{
		startTask(driveComp);
		startTask(armComp);
		startTask(intakeComp);
	}
}
