#pragma config(Sensor, in1,    potright,       sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, in3,    potleft,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  solenoid,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  solenoidhang,   sensorDigitalOut)
#pragma config(Sensor, dgtl9,  solenoidbrake,  sensorDigitalOut)
#pragma config(Motor,  port1,           m_driver2,     tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           m_driver3,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           m_armright2,   tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           m_intaker,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           m_armleft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           m_intakel,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           m_armright,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           m_armleft2,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           m_drivel2,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          m_drivel3,     tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "driveCodeHolo.h" //Contains All Code for Movement of a Holonomic Drive
//#include "driveCodeTank.h"


void pre_Auton()
{
  startTask(ProgramChooser);
}

task auton()
{
  StopTask(ProgramChooser);
  startAuton();
  StartTask(gyroPID);
  switch(auto) {
    case 0: hangingBlue(); break;
    case 1: hangingBlue1(); break;
    case 2: hangingRed(); break;
    case 3: hangingRed1(); break;
    case 4: middleBlue(); break;
    case 5: middleBlue1(); break;
    case 6: middleRed(); break;
    case 7: middleRed1(); break;
    case 8: hangingRedHnG(); break;
    case 9: hangingBlueHng(); break;
    case 10: ProgrammingSkills(); break;
    case 11: BlockRed(); break;
    case 12: BlockBlue(); break;
  }
}

task usercontrol()
{
  startTask(ProgramChooser);
}
